kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: reload
  commands:
  - cd /home/at/demo.crm.alem.school/web-app
  - git pull
  - docker-compose down && docker-compose up -d

trigger:
  branch:
  - master
  event:
  - push
