version: '3'
services:
  appseed-app:
    restart: always
    network_mode: "host"
    env_file: .env
    # build: .
    image: demo
    ports:
      - "5005:5005"
    volumes:
      - ./app:/app
      - ./migrations:/migrations
