version: '3'
# for dev
networks:
  default:
    external:
      name: postgres
services:
  appseed-app:
    restart: always
    # # for production
    # network_mode: "host"
    env_file: .env
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
      - ./migrations:/migrations
